test-v2:
    stage: build
    image: python:2
    script:
    - python -V
    - pip install pyyaml
    - cd proto
    - python tests.py

deploy:
    stage: deploy
    only:
    - master
    tags:
    - cheby-cd
    script:
    - uname -a
    - pwd
    - echo "$CI_COMMIT_SHORT_SHA"
    - echo "$CI_COMMIT_TAG"
